version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: ms-agenda-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:5432"
    networks:
      - ms-agenda-network
    volumes:
      - .docker/local/data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: ms-agenda-redis
    ports:
      - "${REDIS_PORT_EXTERNAL}:6379"
    networks:
      - ms-agenda-network
networks:
  ms-agenda-network:
    driver: bridge